import { generateChatResponse, ChatMessage } from './google-ai';

/**
 * Generates a conversation title from the AI's first response using AI
 * @param aiResponse - The first AI response content
 * @param apiKey - Google AI API key
 * @returns A short, descriptive title generated by AI
 */
export async function generateConversationTitleFromAIResponse(
  aiResponse: string,
  apiKey: string
): Promise<string> {
  if (!aiResponse || aiResponse.trim().length === 0) {
    return "New Conversation";
  }

  try {
    // Truncate the response if it's too long to avoid token limits
    const truncatedResponse = aiResponse.length > 500 
      ? aiResponse.substring(0, 500) + '...' 
      : aiResponse;

    const prompt = `Based on the following AI assistant response, generate a very short, concise conversation title (maximum 5-6 words). The title should capture the main topic or subject of the conversation. Return ONLY the title, nothing else.

AI Response:
${truncatedResponse}

Title:`;

    const messages: ChatMessage[] = [
      {
        role: 'user',
        content: prompt
      }
    ];

    const title = await generateChatResponse(apiKey, messages, {
      temperature: 0.3,
      maxOutputTokens: 50,
      topK: 20,
      topP: 0.8
    });

    // Clean up the title - remove quotes, extra whitespace, and ensure it's not too long
    let cleanTitle = title.trim()
      .replace(/^["']|["']$/g, '') // Remove surrounding quotes
      .replace(/\n/g, ' ') // Replace newlines with spaces
      .replace(/\s+/g, ' ') // Normalize whitespace
      .trim();

    // If title is too long, truncate it
    if (cleanTitle.length > 60) {
      cleanTitle = cleanTitle.substring(0, 57) + '...';
    }

    // If we got a valid title, return it
    if (cleanTitle && cleanTitle.length > 0 && cleanTitle !== 'Title:') {
      return cleanTitle;
    }

    // Fallback to simple extraction if AI didn't return a good title
    return generateConversationTitle(aiResponse);
  } catch (error) {
    console.error('Error generating AI title:', error);
    // Fallback to simple extraction if AI call fails
    return generateConversationTitle(aiResponse);
  }
}

/**
 * Generates a conversation title from the first user message
 * @param firstMessage - The first message content from the user
 * @returns A generated title for the conversation
 */
export function generateConversationTitle(firstMessage: string): string {
  if (!firstMessage || firstMessage.trim().length === 0) {
    return "New Conversation";
  }

  // Clean the message - remove extra whitespace and normalize
  const cleanMessage = firstMessage.trim();
  
  // If message is too short, use it as is
  if (cleanMessage.length <= 30) {
    return cleanMessage;
  }

  // Extract key phrases and words
  const words = cleanMessage.split(/\s+/);
  
  // Remove common stop words and short words
  const stopWords = new Set([
    'the', 'a', 'an', 'and', 'or', 'but', 'in', 'on', 'at', 'to', 'for', 'of', 'with', 'by',
    'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'do', 'does', 'did',
    'will', 'would', 'could', 'should', 'may', 'might', 'can', 'must', 'shall',
    'i', 'you', 'he', 'she', 'it', 'we', 'they', 'me', 'him', 'her', 'us', 'them',
    'this', 'that', 'these', 'those', 'what', 'when', 'where', 'why', 'how', 'who',
    'please', 'thanks', 'thank', 'hello', 'hi', 'hey'
  ]);

  // Filter out stop words and short words, keep important terms
  const importantWords = words
    .filter(word => {
      const cleanWord = word.toLowerCase().replace(/[^\w]/g, '');
      return cleanWord.length > 2 && !stopWords.has(cleanWord);
    })
    .slice(0, 8); // Take first 8 important words

  // If we have important words, create title
  if (importantWords.length > 0) {
    let title = importantWords.join(' ');
    
    // Capitalize first letter of each word for better readability
    title = title.replace(/\b\w/g, l => l.toUpperCase());
    
    // Truncate if still too long
    if (title.length > 50) {
      title = title.substring(0, 47) + '...';
    }
    
    return title;
  }

  // Fallback: take first 30 characters and add ellipsis if needed
  if (cleanMessage.length > 30) {
    return cleanMessage.substring(0, 27) + '...';
  }

  return cleanMessage;
}

/**
 * Checks if a conversation title is the default "New Conversation"
 * @param title - The conversation title to check
 * @returns True if it's the default title
 */
export function isDefaultTitle(title: string): boolean {
  return title === "New Conversation" || title === "Conversation";
}
